os: osx
osx_image: xcode10.2

language: bash

before-cache:
 - brew cleanup
 
cache:
 -directories:
 -$HOME/Library/Caches/HomeBrew

before-install:
 - whoami
 - echo "start of pipeline"
 - HOMEBREW_NO_AUTO_UPDATE=1
   
       
install:
   - whoami
   - echo "start of the pipeline "
   - HOMEBREW_NO_AUTO_UPDATE=1
   
script:
    - ls
    - chmod + hello.sh
    - ./hello.sh
    
after-script:
     - echo "End of pipeline "
